<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-9JB0BLCJ" failures="2" tests="9" name="Test" time="10.784" errors="0" timestamp="2025-07-14T13:28:26 CDT">
  <testcase classname="api.test.UserTests" name="testPostUser" time="3.612"/>
  <testcase classname="api.test.UserTests" name="testGetUserByusername" time="0.503"/>
  <testcase classname="api.test.UserTests" name="testupdateUserByusername" time="0.607"/>
  <testcase classname="api.test.UserTests" name="testdeleteUserByusername" time="0.288"/>
  <testcase classname="api.test.UserTests" name="testPostUserWithArray" time="0.325">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at api.test.UserTests.testPostUserWithArray(UserTests.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testPostUserWithArray -->
  <testcase classname="api.test.DataDrivenUserTests" name="testPostUser" time="0.628"/>
  <testcase classname="api.test.DataDrivenUserTests" name="testPostUser" time="0.615"/>
  <testcase classname="api.test.DataDrivenUserTests" name="testGetUserByUserName" time="0.74">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenUserTests.testGetUserByUserName(DataDrivenUserTests.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByUserName -->
  <testcase classname="api.test.DataDrivenUserTests" name="testGetUserByUserName" time="0.508"/>
</testsuite> <!-- Test -->
