<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="7" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-14T13:28:15 CDT" name="Suite" finished-at="2025-07-14T13:28:25 CDT" duration-ms="10784">
    <groups>
    </groups>
    <test started-at="2025-07-14T13:28:15 CDT" name="Test" finished-at="2025-07-14T13:28:25 CDT" duration-ms="10784">
      <class name="api.test.DataDrivenUserTests">
        <test-method signature="testPostUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.test.DataDrivenUserTests@7a8c8dcf]" started-at="2025-07-14T13:28:23 CDT" name="testPostUser" data-provider="Data" finished-at="2025-07-14T13:28:23 CDT" duration-ms="628" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[1000]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[rakesh001]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Rakesh]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Ravikumar]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[rakesh.ravikumar@email.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[rakesh@1234]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[6151863456]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostUser -->
        <test-method signature="testPostUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.test.DataDrivenUserTests@7a8c8dcf]" started-at="2025-07-14T13:28:23 CDT" name="testPostUser" data-provider="Data" finished-at="2025-07-14T13:28:24 CDT" duration-ms="615" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[1001]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[shruthi001]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Shruthi]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Padmaprabha]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[shruthi.padmaprabha@email.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[shruthi@1234]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[6151868357]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostUser -->
        <test-method signature="testGetUserByUserName(java.lang.String)[pri:2, instance:api.test.DataDrivenUserTests@7a8c8dcf]" started-at="2025-07-14T13:28:24 CDT" name="testGetUserByUserName" data-provider="Usernames" finished-at="2025-07-14T13:28:25 CDT" duration-ms="740" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[rakesh001]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at api.test.DataDrivenUserTests.testGetUserByUserName(DataDrivenUserTests.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserByUserName -->
        <test-method signature="testGetUserByUserName(java.lang.String)[pri:2, instance:api.test.DataDrivenUserTests@7a8c8dcf]" started-at="2025-07-14T13:28:25 CDT" name="testGetUserByUserName" data-provider="Usernames" finished-at="2025-07-14T13:28:25 CDT" duration-ms="508" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[shruthi001]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserByUserName -->
      </class> <!-- api.test.DataDrivenUserTests -->
      <class name="api.test.UserTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.test.UserTests@49438269]" started-at="2025-07-14T13:28:15 CDT" name="setUp" finished-at="2025-07-14T13:28:16 CDT" duration-ms="1244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testPostUser()[pri:1, instance:api.test.UserTests@49438269]" started-at="2025-07-14T13:28:16 CDT" name="testPostUser" finished-at="2025-07-14T13:28:20 CDT" duration-ms="3612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostUser -->
        <test-method signature="testGetUserByusername()[pri:2, instance:api.test.UserTests@49438269]" started-at="2025-07-14T13:28:20 CDT" name="testGetUserByusername" finished-at="2025-07-14T13:28:20 CDT" duration-ms="503" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserByusername -->
        <test-method signature="testupdateUserByusername()[pri:3, instance:api.test.UserTests@49438269]" started-at="2025-07-14T13:28:20 CDT" name="testupdateUserByusername" finished-at="2025-07-14T13:28:21 CDT" duration-ms="607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testupdateUserByusername -->
        <test-method signature="testdeleteUserByusername()[pri:4, instance:api.test.UserTests@49438269]" started-at="2025-07-14T13:28:21 CDT" name="testdeleteUserByusername" finished-at="2025-07-14T13:28:21 CDT" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdeleteUserByusername -->
        <test-method signature="testPostUserWithArray()[pri:5, instance:api.test.UserTests@49438269]" started-at="2025-07-14T13:28:21 CDT" name="testPostUserWithArray" finished-at="2025-07-14T13:28:22 CDT" duration-ms="325" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [500]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at api.test.UserTests.testPostUserWithArray(UserTests.java:107)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostUserWithArray -->
      </class> <!-- api.test.UserTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
